Group and optimize Doxygen steps in the workflow

diff --git a/.github/workflows/build-mac.yml b/.github/workflows/build-mac.yml
--- a/.github/workflows/build-mac.yml
+++ b/.github/workflows/build-mac.yml
@@ -18,6 +18,13 @@ jobs:
     runs-on: macos-11
 
     steps:
+    - name: Cleanup workspace and dependencies
+      run: |
+        rm -rf ${{github.workspace}}/build
+        rm -rf ${{github.workspace}}/html
+        brew uninstall fontconfig freetype openssl libxml2 jpeg-turbo libpng libtiff libidn doxygen || true
+        brew autoremove
+
     - uses: actions/checkout@v2
       with:
           submodules: true
@@ -25,7 +32,7 @@ jobs:
     - name: Install deps
       # NOTE: We need to ensure jpeg-turbo is at least version 2.14
       run: brew update
-           && brew install fontconfig freetype openssl libxml2 jpeg-turbo libpng libtiff libidn
+           && brew install fontconfig freetype openssl libxml2 jpeg-turbo libpng libtiff libidn doxygen
 
     - name: Configure CMake
       # NOTE: OpenSSL prefix must be explicitly set
@@ -39,13 +46,19 @@ jobs:
       working-directory: ${{github.workspace}}/build
       run: ctest ${{ github.event.inputs.ctestArgs }}
 
-    - name: Install Doxygen
-      run: brew install doxygen
+    - name: Generate Doxygen Documentation
+      run: |
+        doxygen Doxyfile
+        if [ -d "./html" ]; then
+          echo "Doxygen documentation generated successfully."
+        else
+          echo "Failed to generate Doxygen documentation." && exit 1
+        fi
+      id: doxygen
+      continue-on-error: true
 
-    - name: Generate Doxygen documentation
-      run: doxygen Doxyfile
-
-    - name: Upload Doxygen documentation
+    - name: Upload Doxygen Documentation
+      if: steps.doxygen.outcome == 'success'
       uses: actions/upload-artifact@v2
       with:
         name: documentation
